/*
 * Auto-generated by Frida. Please modify to match the signature of -[SBIconRotationContainer initWithFrame:startIcon:endIcon:iconViewProvider:coordinate:location:transitionAnimation:offscreen:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: http://www.frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call -[SBIconRotationContainer initWithFrame:startIcon:endIcon:iconViewProvider:coordinate:location:transitionAnimation:offscreen:].
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('-[SBIconRotationContainer initWithFrame:' + args[2] + ' startIcon:' + args[3] + ' endIcon:' + args[4] + ' iconViewProvider:' + args[5] + ' coordinate:' + args[6] + ' location:' + args[7] + ' transitionAnimation:' + args[8] + ' offscreen:' + args[9] + ']');
  },

  /**
   * Called synchronously when about to return from -[SBIconRotationContainer initWithFrame:startIcon:endIcon:iconViewProvider:coordinate:location:transitionAnimation:offscreen:].
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
  }
}
